In [1]:
import numpy as np
import pickle
from numpy import linalg as LA
import math

In [2]:
ratingsMatrix = []
with open('ratingsMatrix_noZeros.pickle','rb') as file:
    ratingsMatrix = pickle.load(file)

In [5]:
A = ratingsMatrix
U_val, U = LA.eig(np.matmul(A, A.T))
V_val, V = LA.eig(np.matmul(A.T, A))

In [40]:
a = sorted(zip(U, U_val), key=lambda x: x[0], reverse = True)
b = sorted(zip(V, V_val), key=lambda x: x[0], reverse = True)
for i in range(5):
    print(a[i][1], b[i][1])
    if not np.isclose(a[i][0],b[i][0]):
        print(np.isclose(a[i][0],b[i][0]))

[-0.00471786+0.j         -0.00164551+0.j          0.00267141+0.j
 ...  0.00275575-0.00013736j  0.00141148-0.00143245j
  0.00141148+0.00143245j] [-7.01371394e-02+0.00000000e+00j  2.09401541e-02+0.00000000e+00j
 -3.01647236e-02+0.00000000e+00j ...  6.11120451e-17-3.74589477e-17j
 -3.76603172e-17+0.00000000e+00j -1.44557167e-16+0.00000000e+00j]
[-9.28855590e-03+0.00000000e+00j  2.69781903e-03+0.00000000e+00j
  3.82152933e-04+0.00000000e+00j ...  1.96428529e-04-8.93236119e-07j
  8.62438569e-05-5.74854326e-05j  8.62438569e-05+5.74854326e-05j] [-2.35438150e-02+0.00000000e+00j  2.97924550e-02+0.00000000e+00j
  1.01890706e-02+0.00000000e+00j ...  6.75998066e-17+5.76040886e-17j
  1.46046739e-16+0.00000000e+00j  1.70723662e-15+0.00000000e+00j]
[-0.00501018+0.00000000e+00j  0.00334292+0.00000000e+00j
 -0.00334366+0.00000000e+00j ...  0.00034157-3.20156197e-06j
  0.00020166-2.08732352e-04j  0.00020166+2.08732352e-04j] [-1.37658393e-02+0.00000000e+00j  1.67038987e-02+0.00000000e+00j
 -1.25724193e-0

In [47]:
singularValues = []
for i in V:
    singularValues.append((i**0.5))
sigma = np.diag(singularValues)
print(sigma)

[[1.89321056e+03+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j ... 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 6.71343565e+02+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j ... 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  5.74852760e+02+0.00000000e+00j ... 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 ...
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j ... 7.64035471e-08-1.26441901e-08j
  0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j ... 0.00000000e+00+0.00000000e+00j
  5.48720326e-08+0.00000000e+00j 0.00000000e+00+0.00000000e+00j]
 [0.000000

In [53]:
# print(U_val[:,:sigma.shape[0]].shape, sigma.shape)
np.matmul(np.matmul(U_val[:,:sigma.shape[0]], sigma), V_val)

array([[ 0.20883196-2.02758458e-10j,  1.12992785-1.66609762e-10j,
         1.16083581-4.87075243e-11j, ...,  0.09306564+4.22438642e-02j,
        -0.09998234+2.37129489e-26j,  0.03256178-1.78357049e-23j],
       [ 0.2305989 -5.04311603e-11j, -0.53239792-8.20046688e-11j,
         0.44498017-8.78807994e-11j, ..., -0.28835923-1.76351841e-01j,
         0.34614035-7.66639913e-24j, -0.15135676+8.09741457e-24j],
       [ 0.28643325-2.74244042e-10j,  0.14275465-3.45814338e-10j,
         0.34432598-3.65003325e-10j, ..., -0.02719077-4.80290485e-03j,
         0.01766245+4.55938624e-24j, -0.1290428 +2.07191513e-24j],
       ...,
       [ 0.57439791+3.61653867e-10j, -0.16428786-2.75041018e-11j,
         0.73194859+8.54978259e-10j, ...,  0.18601728+1.36387052e-02j,
        -0.12175623-8.87753365e-23j,  0.26888851+1.71177884e-22j],
       [ 1.29358725-4.90746631e-10j, -0.43270849-2.68837369e-10j,
         0.37274928-1.18502383e-09j, ..., -0.08016025+1.29112127e-02j,
         0.02707447-1.27344966e-23j

In [3]:
u, s, vh = LA.svd(ratingsMatrix)

In [5]:
u.shape, s.shape, vh.shape

((6040, 6040), (3706,), (3706, 3706))

In [4]:
reR = np.matmul((np.matmul(u[:, :3706], np.diag(s))), vh)
reR[reR < 1e-5] = 0
print(np.allclose(reR, ratingsMatrix))
reR

True


array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [3., 0., 0., ..., 0., 0., 0.]])

In [5]:
ratingsMatrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [3., 0., 0., ..., 0., 0., 0.]])

In [62]:
s1, u1 = LA.eig(np.matmul(ratingsMatrix, ratingsMatrix.T))

In [51]:
s1[s1 < 1e-5] = 0
np.allclose(np.array(sorted(s1)[::-1])[:3706]**0.5, s)

True

In [65]:
from scipy import linalg
s1r, u1r = linalg.cdf2rdf(s1, u1)

In [88]:
x = sorted(zip(s,u), key = lambda x: x[0], reverse = True)
y = sorted(zip(s1r,u1r), key = lambda x: x[0], reverse = True)
for i in range(3706):
    # print(x[i][0], y[i][0]**0.5)
    print(x[0][1][i], y[0][1][i])    

-0.004717857732089549 -0.004717857732089501
0.0016455069760065288 -0.0016455069760064138
0.002671408404032269 0.002671408404032254
0.001372879654849866 0.0013728796548494984
0.018725916125247787 0.018725916125247908
-0.008714471881469869 0.00871447188146977
0.005196537331031096 0.005196537331031195
-0.004360621196221009 0.004360621196221019
-0.018942189490224498 -0.018942189490224498
-0.013255434359443827 0.013255434359443855
-0.007040185369583638 -0.00704018536958346
0.005817832412263016 0.005817832412262984
0.013200590523790365 0.013200590523790188
-0.0040373190179704985 -0.004037319017970081
0.015945021169684152 0.015945021169684492
-0.004292842986221737 -0.004292842986221769
0.010470420311729784 -0.010470420311729773
-0.0024176096211173813 -0.0024176096211172525
-0.0016324386451804607 -0.0016324386451804286
-0.00878850345553539 0.008788503455535368
6.398673445960038e-06 6.398673446002548e-06
-0.004303020689082642 -0.004303020689083743
0.015472874758755117 0.015472874758755117
-0.00

-0.009185491598841976 -0.002666354767238255
-0.010556968725139735 -0.006917207425685652
-0.017180502602794176 0.022272047469359995
-0.00909794643542902 0.020326332419227745
0.009868204288296576 -0.0008381341546623535
0.0015463102705766136 0.021582446934163023
0.0019223520216223552 -0.001679919701639316
0.0091921805323576 0.011414662580324269
-0.007568270910458728 0.002820020017551817
-0.0016572171031798393 0.0020814094410034813
0.013610130423008444 -0.007116613201342614
0.024162532172013883 -0.025631126542902248
0.006460934199220829 -0.012996272380279467
0.0027336225992728677 -0.0033540117455022043
0.004158525182097035 -0.005936175467687694
0.0013655073220939678 0.01162962594501653
0.02262352394639609 0.0047509330832008305
-0.026022818082173323 -0.01864198744645269
-0.0006759659999307418 0.0009608147012779385
-0.01650981193725447 -0.016098107595625445
0.003033244367051373 -0.002041544772626536
0.009136800189105607 0.011282496343441818
0.011656915237241218 0.009770013485496507
-0.006776

In [91]:
s11, vh1 = LA.eig(np.matmul(ratingsMatrix.T, ratingsMatrix))

In [97]:
s11r, vh1r = linalg.cdf2rdf(s11, vh1)

In [99]:
s11r = np.array([s11r[i][i] for i in range(len(s11r))])
z = sorted(zip(s11r,vh1r), key = lambda x: x[0], reverse = True)

In [101]:
x = sorted(zip(s1r,u1r), key = lambda x: x[0], reverse = True)
y = sorted(zip(s11r,vh1r), key = lambda x: x[0], reverse = True)
# u1r.shape, s11r.shape, vh1r.shape
# reR = np.matmul((np.matmul(u[:, :3706], np.diag(s))), vh)

In [126]:
a = np.array([x[i][1] for i in range(len(x))])
b = np.array([x[i][0] for i in range(len(y))])
b[b < 1e-5] = 0
c = np.array([y[i][1] for i in range(len(y))])
reR_d = np.matmul((np.matmul(a[:, :3706], np.diag(b**0.5))), c)

In [127]:
reR_d

array([[ 0.46338879,  0.20351824,  0.56245286, ..., -0.05603234,
         0.06404688, -0.29796811],
       [ 0.37060021, -0.43899538, -0.42161456, ..., -0.50450517,
         0.44303211, -0.24516386],
       [ 0.11321587, -0.49233089, -0.03500735, ..., -0.01570973,
        -0.04603041,  0.18216406],
       ...,
       [ 3.66300649, -0.90192272,  1.27773191, ...,  0.2189592 ,
        -0.23122049,  0.01057144],
       [ 1.29398095, -0.53799334, -0.63157762, ..., -0.04134939,
         0.18809833, -0.85782978],
       [ 1.8417867 , -0.94488479,  2.09904726, ...,  0.13723401,
        -0.14017295,  0.42591666]])

In [8]:
s1t = np.copy(s1)
s11t = np.copy(s11)
u1t = np.copy(u1)
vh1t = np.copy(vh1)

In [9]:
s1[s1 < 1e-5] = 0
s[s < 1e-5] = 0
s11[s11 < 1e-5] = 0

In [10]:
s1 = s1[::-1]**0.5
s11 = s11[::-1]**0.5
u1 = u1[::-1]
vh1 = vh1[::-1]

In [11]:
# u1[:, :3706].shape, np.diag(s11).shape, vh1.shape
# reR1 = np.matmul((u1[:, :3706]*s11), vh1)
k = u1[:, :3706]*s11

In [21]:
k1 = np.copy(k)
k1[k1 < 1e-5] = 0
vh11 = np.copy(vh1)
vh11[vh11 < 1e-5] = 0
np.dot(k1, vh11)

array([[0.05130306, 0.0992467 , 0.12664369, ..., 1.32912083, 1.09755408,
        2.62077767],
       [0.09547431, 0.22896479, 0.1298593 , ..., 2.56933873, 2.28816544,
        5.49145594],
       [0.09996249, 0.06856339, 0.08550545, ..., 2.87578327, 2.57071263,
        5.84273904],
       ...,
       [0.03292029, 0.03406224, 0.02870564, ..., 0.32601751, 0.21031172,
        0.90940072],
       [0.01715801, 0.03074977, 0.0774072 , ..., 0.28359952, 0.15396737,
        0.57812738],
       [0.00899205, 0.06748556, 0.10401575, ..., 0.29826257, 0.23320506,
        0.49510615]])

In [20]:
s

array([1893.21055869,  671.34356538,  574.85275997, ...,    0.        ,
          0.        ,    0.        ])

In [57]:
a = np.unwrap(np.isclose((s1[::-1]**0.5)[:3706],s))

In [58]:
for i in range (len(a)):
    if not a[i]:
        print(s[i], (s1[::-1]**0.5)[:3706][i])

In [60]:
np.allclose(s, (s1[::-1]**0.5)[:3706])

True

In [72]:
vh1[::-1].shape

(3706, 3706)

In [68]:
u

array([[-4.71785773e-03+0.j,  1.64550698e-03+0.j,  2.67140840e-03+0.j,
        ...,  1.67951445e-02+0.j, -1.18720109e-02+0.j,
        -1.45902989e-02+0.j],
       [-9.28855590e-03+0.j, -2.69781903e-03+0.j,  3.82152933e-04+0.j,
        ..., -1.66247945e-03+0.j, -1.63347902e-02+0.j,
        -1.71135367e-02+0.j],
       [-5.01017861e-03+0.j, -3.34291508e-03+0.j, -3.34366161e-03+0.j,
        ...,  1.52841300e-03+0.j,  1.17703079e-02+0.j,
         1.17760840e-03+0.j],
       ...,
       [-1.38885083e-03+0.j,  1.81338730e-03+0.j, -1.18789245e-04+0.j,
        ...,  7.80954716e-01+0.j, -3.12055243e-03+0.j,
        -7.54086672e-03+0.j],
       [-7.00792837e-03+0.j,  1.87647017e-02+0.j, -1.07122502e-02+0.j,
        ..., -9.81735690e-03+0.j,  3.46962725e-01+0.j,
        -1.94480433e-03+0.j],
       [-1.89610238e-02+0.j,  4.08024430e-02+0.j, -3.04316280e-03+0.j,
        ..., -1.43574957e-03+0.j, -3.37810817e-03+0.j,
         8.63670504e-02+0.j]])

In [ ]:
u1 = u1[::-1]
vh1 = vh1[::-1]
s11 = s11[::-1]
reRR_ = np.matmul((np.matmul(u1[:, :3706], np.diag(s11))), vh1)
reRR_